version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot\shapestore
hooks:
  BeforeInstall:
    - location: _scripts/install_dependencies.bat
      timeout: 300
      runas: administrator
  ApplicationStop:
    - location: _scripts/stop_server.bat
      timeout: 300
      runas: administrator
  ApplicationStart:
    - location: _scripts/start_server.bat
      timeout: 300
      runas: administrator
  ValidateService:
    - location: _scripts/verify_service.bat
      timeout: 300
      runas: administrator

