#!/bin/bash
# yum install -y httpd
# install server manager and iis if not already installed....
powershell.exe -Command Import-Module -Name ServerManager
powershell.exe -Command Install-WindowsFeature Web-Server -IncludeAllSubFeature -IncludeManagementTools
